throttling.c:  null terminate input buffer
An SAST run reported the following in src/throttling.c:
    Error: STRING_NULL (CWE-170):
    stalld-1.17.1/src/throttling.c:70: string_null_source: Function "read" does not terminate string "buffer". [Note: The source code implementation of the function has been overridden by a builtin model.]
    stalld-1.17.1/src/throttling.c:74: string_null: Passing unterminated string "buffer" to "strtol", which expects a null-terminated string.
    #   72|                   die("failed to read %s\n", RT_RUNTIME_PATH);
    #   73|
    #   74|->         rt_runtime_us = strtol(buffer, NULL, 10);
    #   75|
    #   76|           if (rt_runtime_us == -1) {

Call memset before reading into the buffer to ensure that the input
string is null terminated.

Signed-off-by: Clark Williams <williams@redhat.com>